name: 'Build'

description: 'Building'

inputs:
  os:
    description: 'os name'
    required: true
    default: 'windows-latest'
  compiler:
    description: 'compiler'
    required: true
    default: 'llvm'
  build_type:
    description: 'Debug or Release'
    required: true
    default: 'Debug'
  build_dir:
    description: 'Build folder'
    required: false
    default: 'build'
  cmake_flags:
    description: 'Flags for CMake configuration'
    required: false
    default: ''
  cmake_target:
    description: 'Cmake target'
    required: false
    default: 'all'

runs:
  using: composite
  steps:
    - name: Setup Cpp
      uses: aminya/setup-cpp@v1.7.2
      with:
        compiler: ${{ inputs.compiler }}
        vcvarsall: ${{ contains(inputs.os, 'windows' ) && !contains(inputs.os, 'arm' )}}
        cmake: true
        ninja: true
        vcpkg: false

    - name: Configure CMake
      shell: bash
      run: cmake -S . -B "${{ inputs.build_dir }}" -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DCMAKE_TLS_VERIFY=0 ${{ inputs.cmake_flags }}

    - name: Build
      shell: bash
      run: cmake --build "${{ inputs.build_dir }}" --config ${{ inputs.build_type }} --target ${{ inputs.cmake_target }} --parallel