name: 'Build'

description: 'Building'

inputs:
  compiler:
    description: 'compiler'
    required: true
    default: 'llvm'
  build_type:
    description: 'Debug or Release'
    required: true
    default: 'Debug'
  build_dir:
    description: 'Build folder'
    required: false
    default: 'build'
  cmake_flags:
    description: 'Flags for CMake configuration'
    required: false
    default: ''
  cmake_target:
    description: 'Cmake target'
    required: false
    default: 'all'

runs:
  using: composite
  steps:
    - name: Setup Cpp
      uses: aminya/setup-cpp@v1.8.0
      with:
        compiler: ${{ inputs.compiler }}
        vcvarsall: ${{ contains(runner.os, 'Windows') && !contains(runner.os, 'arm') }}
        cmake: true
        ninja: true
        vcpkg: false

    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ccache
          ~/.ccache
          ~/.config/ccache
          ~/Library/Caches/ccache
        key: ${{ runner.os }}-ccache-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ inputs.compiler }}-${{ inputs.build_type }}-
          ${{ runner.os }}-ccache-${{ inputs.compiler }}-
          ${{ runner.os }}-ccache-

    - name: Cache CMake and related caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/cmake
          ~/.cmake
          ~/.local/share/cmake
        key: ${{ runner.os }}-cmake-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-${{ inputs.compiler }}-${{ inputs.build_type }}-
          ${{ runner.os }}-cmake-${{ inputs.compiler }}-
          ${{ runner.os }}-cmake-

    - name: Configure CMake
      shell: bash
      run: cmake -S . -B "${{ inputs.build_dir }}" -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DCMAKE_TLS_VERIFY=0 ${{ inputs.cmake_flags }}

    - name: Build
      shell: bash
      run: cmake --build "${{ inputs.build_dir }}" --target ${{ inputs.cmake_target }} --parallel