name: 'Build'

description: 'Building'

inputs:
  build_type:
    description: 'Debug or Release'
    required: true
    default: 'Debug'
  cmake_flags:
    description: 'Flags for CMake configuration'
    required: false
    default: ''
  cmake_target:
    description: 'Cmake target'
    required: false
    default: 'all'
  abi:
    description: 'ABI'
    required: true

runs:
  using: composite
  steps:
    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_TLS_VERIFY=0 \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=${{ inputs.abi }} \
        ${{ inputs.cmake_flags }}

    - name: Build
      shell: bash
      run: cmake --build build --target ${{ inputs.cmake_target }} --config ${{ inputs.build_type }} --parallel
