name: 'Build'

description: 'Building'

inputs:
  build_type:
    description: 'Debug or Release'
    required: true
    default: 'Debug'
  build_dir:
    description: 'Build directory'
    required: false
    default: 'build'
  cmake_flags:
    description: 'Flags for CMake configuration'
    required: false
    default: ''
  cmake_target:
    description: 'Cmake target'
    required: false
    default: 'all'
  abi:
    description: 'ABI'
    required: true

runs:
  using: composite
  steps:
    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ccache
          ~/.ccache
          ~/.config/ccache
        key: ${{ runner.os }}-android-ccache-${{ inputs.abi }}-${{ inputs.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-android-ccache-${{ inputs.abi }}-${{ inputs.build_type }}-
          ${{ runner.os }}-android-ccache-${{ inputs.abi }}-
          ${{ runner.os }}-android-ccache-

    - name: Cache CMake & Android caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/cmake
          ~/.cmake
          ~/.android
        key: ${{ runner.os }}-android-cmake-${{ inputs.abi }}-${{ inputs.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-android-cmake-${{ inputs.abi }}-${{ inputs.build_type }}-
          ${{ runner.os }}-android-cmake-${{ inputs.abi }}-
          ${{ runner.os }}-android-cmake-

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B ${{ inputs.build_dir }} -DCMAKE_TLS_VERIFY=0 \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=${{ inputs.abi }} \
        -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
        ${{ inputs.cmake_flags }}

    - name: Build
      shell: bash
      run: cmake --build ${{ inputs.build_dir }} --target ${{ inputs.cmake_target }} --parallel
