name: 'Build'

description: 'Building'

inputs:
  emsdk_version:
    description: 'Version of emsdk'
    required: false
    default: 'latest'
  cmake_flags:
    description: 'Flags for CMake configuration'
    required: false
    default: ''
  build_type:
    description: 'Debug or Release'
    required: true
    default: 'Debug'
  build_dir:
    description: 'Build dir'
    required: false
    default: 'build'
  cmake_target:
    description: 'Cmake target'
    required: false
    default: 'all'
runs:
  using: composite
  steps:

    - name: Cache emsdk
      uses: actions/cache@v3
      with:
        path: emsdk-cache
        key: emsdk-${{ runner.os }}-${{ inputs.emsdk_version }}
        restore-keys: |
          emsdk-${{ runner.os }}-

    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ccache
          ~/.ccache
          ~/.config/ccache
          ~/Library/Caches/ccache
        key: ${{ runner.os }}-emscripten-ccache-${{ inputs.emsdk_version }}-${{ inputs.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-emscripten-ccache-${{ inputs.emsdk_version }}-${{ inputs.build_type }}-
          ${{ runner.os }}-emscripten-ccache-${{ inputs.emsdk_version }}-
          ${{ runner.os }}-emscripten-ccache-

    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emsdk_version }}
        actions-cache-folder: emsdk-cache

    - name: Configure
      shell: bash
      run: emcmake cmake -S . -B ${{ inputs.build_dir }} -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} "${{ inputs.cmake_flags }}"

    - name: Build
      shell: bash
      run: cmake --build ${{ inputs.build_dir }} --target ${{ inputs.cmake_target }} --parallel