name: 'Build'

description: 'Building'

inputs:
  emsdk_version:
    description: 'Version of emsdk'
    required: false
    default: '5.0.0'
  cmake_flags:
    description: 'Flags for CMake configuration'
    required: false
    default: ''
  build_type:
    description: 'Debug or Release'
    required: true
    default: 'Debug'
  cmake_target:
    description: 'Cmake target'
    required: false
    default: 'all'
runs:
  using: composite
  steps:

    - name: Set environment variables
      shell: bash
      run: echo "EMSDK_PATH=$HOME/emsdk" >> $GITHUB_ENV

    - name: Cache emsdk
      uses: actions/cache@v3
      with:
        path: ~/emsdk
        key: emsdk-${{ runner.os }}-${{ inputs.emsdk_version }}

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emsdk_version }}

    - name: Configure
      shell: bash
      run: emcmake cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} ${{ inputs.cmake_flags }}

    - name: Build
      shell: bash
      run: cmake --build build --target ${{ inputs.cmake_target }} --config ${{ inputs.build_type }} --parallel