name: 'Build'

description: 'Building'

inputs:
  emsdk_version:
    description: 'Version of emsdk'
    required: false
    default: 'latest'
  cmake_flags:
    description: 'Flags for CMake configuration'
    required: false
    default: ''
  build_type:
    description: 'Debug or Release'
    required: true
    default: 'Debug'
  cmake_target:
    description: 'Cmake target'
    required: false
    default: 'all'
runs:
  using: composite
  steps:

    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: emsdk-cache
        key: ${{ inputs.emsdk_version }}-${{ runner.os }}

    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emsdk_version }}
        actions-cache-folder: emsdk-cache

    - name: Configure
      shell: bash
      run: emcmake cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} ${{ inputs.cmake_flags }}

    - name: Build
      shell: bash
      run: cmake --build build --target ${{ inputs.cmake_target }} --config ${{ inputs.build_type }} --parallel