name: CMake on Windows with Multiple Compilers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        compiler: [msvc, mingw, clang, clang-cl, intel]
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up compiler
      shell: pwsh
      run: |
        $compiler = "${{ matrix.compiler }}"
        echo "MATRIX_COMPILER=$compiler" | Out-File -FilePath $env:GITHUB_ENV -Append

        if ($compiler -eq "mingw") {
          Write-Host "Using MinGW"
          choco install mingw
          echo "CC=gcc" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CXX=g++" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CMAKE_GENERATOR=MinGW Makefiles" | Out-File -FilePath $env:GITHUB_ENV -Append
        } elseif ($compiler -eq "clang") {
          Write-Host "Using Clang"
          choco install llvm
          echo "CC=clang" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CXX=clang++" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CMAKE_GENERATOR=Ninja" | Out-File -FilePath $env:GITHUB_ENV -Append
        } elseif ($compiler -eq "clang-cl") {
          Write-Host "Using Clang-cl (MSVC compatible Clang)"
          choco install llvm
          echo "CC=clang-cl" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CXX=clang-cl" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CMAKE_GENERATOR=Visual Studio 17 2022" | Out-File -FilePath $env:GITHUB_ENV -Append
        } elseif ($compiler -eq "intel") {
          Write-Host "Using Intel oneAPI Compiler"
          Invoke-WebRequest -Uri https://registrationcenter-download.intel.com/akdlm/IRC_NAS/18964/w_BaseKit_p_2024.0.0.49547_offline.exe -OutFile intel.exe
          Start-Process -Wait -FilePath .\intel.exe -ArgumentList "/silent", "/install"
          echo "CC=icx" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CXX=icpx" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CMAKE_GENERATOR=Ninja" | Out-File -FilePath $env:GITHUB_ENV -Append
        } else {
          Write-Host "Using MSVC"
          echo "CC=cl" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CXX=cl" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "CMAKE_GENERATOR=Visual Studio 17 2022" | Out-File -FilePath $env:GITHUB_ENV -Append
        }
