name: CMake on a Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        compiler: [msvc, mingw, clang]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up compiler
      run: |
        if [ "${{ matrix.compiler }}" == "mingw" ]; then
          echo "Using MinGW"
          choco install mingw
        elif [ "${{ matrix.compiler }}" == "clang" ]; then
          echo "Using Clang"
          choco install llvm
        else
          echo "Using MSVC"
        fi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
