name: Windows MinGW CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Latest MinGW (GCC 13+)
        run: |
          choco install mingw --version=13.2.0 -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

      - name: Install CMake 3.25
        uses: milliewalky/setup-cmake@v1
        with:
          cmake-version: '3.25.0'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Verify Tools
        run: |
          g++ --version
          cmake --version
          ninja --version

      - name: Configure CMake
        run: cmake -B build -G "Ninja" -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my_program
          path: build/
