name: Build Windows (GCC)

on:
  push:
  pull_request:

jobs:
  build:
    name: MSYS2 Build (${{ matrix.build_type }})
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
        update: true

    - name: Configure and Build
      shell: msys2 {0}
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build build --target all

    - name: Add DLLs to PATH
      shell: msys2 {0}
      run: |
        echo "Adding mingw64 bin to PATH"
        export PATH="$MSYS2_PATH/mingw64/bin:$PATH"

    - name: Run tests
      shell: msys2 {0}
      working-directory: ./build
      run: ctest --output-on-failure