name: Build Windows (MSVC)

on:
  push:
  pull_request:

jobs:
  build-release_msvc:
    name: Build Release Msvc
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (Release)
        run: cmake -G "Ninja" -B build/release -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build/release

  build-debug_msvc:
    name: Build Debug Msvc
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (Debug)
        run: cmake -G "Ninja" -B build/debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build (Debug)
        run: cmake --build build/debug
