name: Build Windows (MSVC)

on:
  push:
  pull_request:

jobs:
  build-release_msvc:
    name: Build Release Msvc
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (Release)
        run: cmake -G "Ninja" -B build/release -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build/release

      - name: Run the executable for 30 seconds
        shell: pwsh
        run: |
          $process = Start-Process -FilePath ".\build\Release\Engine.exe" -PassThru

          # Let it run for 30 seconds
          Start-Sleep -Seconds 30

          # Terminate the process after 30 seconds
          Stop-Process -Id $process.Id

  build-debug_msvc:
    name: Build Debug Msvc
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (Debug)
        run: cmake -G "Ninja" -B build/debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build (Debug)
        run: cmake --build build/debug

      - name: Run the executable for 30 seconds
        shell: pwsh
        run: |
          $process = Start-Process -FilePath ".\build\Debug\Engine.exe" -PassThru

          # Let it run for 30 seconds
          Start-Sleep -Seconds 30

          # Terminate the process after 30 seconds
          Stop-Process -Id $process.Id
