name: Build Windows (MSVC)

on:
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.build_type }} MSVC
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
        include:
          - build_type: Release
            build_dir: build/release
          - build_type: Debug
            build_dir: build/debug

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (${{ matrix.build_type }})
        run: cmake -G "Ninja" -B ${{ matrix.build_dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build (${{ matrix.build_type }})
        run: cmake --build ${{ matrix.build_dir }}

      - name: Run tests
        working-directory: ./build
        run: ctest --output-on-failure